from enum import StrEnum


class LaneV1(StrEnum):
    DEAL_PRIORITIZATION = "DEAL_PRIORITIZATION"
    ASSIGNMENT_RECOMMENDATION = "ASSIGNMENT_RECOMMENDATION"
    CAPACITY_HEATMAP = "CAPACITY_HEATMAP"


class SourceModeV1(StrEnum):
    FICTIONAL = "FICTIONAL"
    FILE_IMPORT = "FILE_IMPORT"
    DIRECT_CONNECTOR = "DIRECT_CONNECTOR"
    MOCK_REPLAY = "MOCK_REPLAY"


class DataClassificationV1(StrEnum):
    FICTIONAL = "FICTIONAL"
    AUTHORIZED_INTERNAL = "AUTHORIZED_INTERNAL"
    AUTHORIZED_PRIVATE_TRANSCRIPT = "AUTHORIZED_PRIVATE_TRANSCRIPT"


class SnapshotSemanticsV1(StrEnum):
    FULL_SNAPSHOT = "FULL_SNAPSHOT"
    BOUNDED_DELTA = "BOUNDED_DELTA"
    REPLAY_FIXTURE = "REPLAY_FIXTURE"


class ExecutionModeV1(StrEnum):
    FICTIONAL_REPLAY = "FICTIONAL_REPLAY"
    FILE_IMPORT = "FILE_IMPORT"
    DIRECT_CONNECTOR_ENABLED = "DIRECT_CONNECTOR_ENABLED"
    DIRECT_CONNECTOR_DISABLED = "DIRECT_CONNECTOR_DISABLED"


class ImplementationProofV1(StrEnum):
    FULLY_IMPLEMENTED_CONTRACT_TESTED = "FULLY_IMPLEMENTED_CONTRACT_TESTED"
    MOCK_TESTED_ONLY = "MOCK_TESTED_ONLY"
    ADAPTER_INTERFACE_ONLY = "ADAPTER_INTERFACE_ONLY"


class LiveValidationProofV1(StrEnum):
    NOT_LIVE_VALIDATED = "NOT_LIVE_VALIDATED"
    LIVE_SANDBOX_VALIDATED = "LIVE_SANDBOX_VALIDATED"
