from __future__ import annotations

from typing import Protocol

from orchestrator.contracts.adapter import AdapterCapabilityV1


class SourceAdapter(Protocol):
    """Phase 0 shape only; adapter implementations begin in later named phases."""

    def capability(self) -> AdapterCapabilityV1: ...
    def preflight(self, auth: object, request: object) -> object: ...
    def describe(self, request: object) -> object: ...
    def preview(self, request: object) -> object: ...
    def read_page(self, request: object, cursor: object | None) -> object: ...
    def deletion_page(self, request: object, cursor: object | None) -> object: ...
